import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const statements = [
  `CREATE TABLE IF NOT EXISTS "Estimate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "customerName" TEXT,
    "drawingFileName" TEXT,
    "memo" TEXT,
    "quoteType" TEXT NOT NULL DEFAULT 'NORMAL',
    "materialCost" INTEGER NOT NULL DEFAULT 0,
    "processingCost" INTEGER NOT NULL DEFAULT 0,
    "setupCost" INTEGER NOT NULL DEFAULT 0,
    "finishingCost" INTEGER NOT NULL DEFAULT 0,
    "inspectionCost" INTEGER NOT NULL DEFAULT 0,
    "packingCost" INTEGER NOT NULL DEFAULT 0,
    "prototypeCost" INTEGER NOT NULL DEFAULT 0,
    "outsourcingCost" INTEGER NOT NULL DEFAULT 0,
    "consumableCost" INTEGER NOT NULL DEFAULT 0,
    "riskCost" INTEGER NOT NULL DEFAULT 0,
    "profit" INTEGER NOT NULL DEFAULT 0,
    "quoteAmount" INTEGER NOT NULL DEFAULT 0,
    "grossMarginRate" REAL NOT NULL DEFAULT 0,
    "issuedAt" DATETIME,
    "expiresAt" DATETIME,
    "quoteNote" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "EstimateMaterial" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "estimateId" TEXT NOT NULL,
    "materialId" TEXT,
    "materialName" TEXT NOT NULL,
    "category" TEXT,
    "thickness" REAL,
    "sheetWidth" REAL NOT NULL,
    "sheetLength" REAL NOT NULL,
    "supplier" TEXT,
    "unitPrice" INTEGER NOT NULL,
    "shippingCost" INTEGER NOT NULL DEFAULT 0,
    "lossRate" REAL NOT NULL DEFAULT 0,
    "requiredWidth" REAL NOT NULL,
    "requiredLength" REAL NOT NULL,
    "quantity" INTEGER NOT NULL,
    "yieldRate" REAL NOT NULL DEFAULT 1,
    "extraRate" REAL NOT NULL DEFAULT 0,
    "requiredArea" REAL NOT NULL DEFAULT 0,
    "sheetArea" REAL NOT NULL DEFAULT 0,
    "requiredSheets" INTEGER NOT NULL DEFAULT 0,
    "materialCost" INTEGER NOT NULL DEFAULT 0,
    "lossCost" INTEGER NOT NULL DEFAULT 0,
    "totalCost" INTEGER NOT NULL DEFAULT 0,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "EstimateMaterial_estimateId_fkey" FOREIGN KEY ("estimateId") REFERENCES "Estimate" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "EstimateMaterial_materialId_fkey" FOREIGN KEY ("materialId") REFERENCES "Material" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "EstimateProcessing" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "estimateId" TEXT NOT NULL,
    "requiredQuantity" INTEGER NOT NULL DEFAULT 1,
    "partsPerRun" INTEGER NOT NULL DEFAULT 1,
    "minutesPerRun" REAL NOT NULL DEFAULT 0,
    "setupMinutes" REAL NOT NULL DEFAULT 0,
    "toolChangeMinutes" REAL NOT NULL DEFAULT 0,
    "finishingMinutes" REAL NOT NULL DEFAULT 0,
    "inspectionMinutes" REAL NOT NULL DEFAULT 0,
    "packingMinutes" REAL NOT NULL DEFAULT 0,
    "runCount" INTEGER NOT NULL DEFAULT 0,
    "machineMinutes" REAL NOT NULL DEFAULT 0,
    "totalWorkMinutes" REAL NOT NULL DEFAULT 0,
    "machineRate" INTEGER NOT NULL DEFAULT 0,
    "setupRate" INTEGER NOT NULL DEFAULT 0,
    "handworkRate" INTEGER NOT NULL DEFAULT 0,
    "finishingRate" INTEGER NOT NULL DEFAULT 0,
    "processingCost" INTEGER NOT NULL DEFAULT 0,
    "setupCost" INTEGER NOT NULL DEFAULT 0,
    "finishingCost" INTEGER NOT NULL DEFAULT 0,
    "inspectionCost" INTEGER NOT NULL DEFAULT 0,
    "packingCost" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "EstimateProcessing_estimateId_fkey" FOREIGN KEY ("estimateId") REFERENCES "Estimate" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "EstimateProcessing_estimateId_key" ON "EstimateProcessing"("estimateId")`,
  `CREATE TABLE IF NOT EXISTS "EstimatePrototype" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "estimateId" TEXT NOT NULL,
    "dataCheckCost" INTEGER NOT NULL DEFAULT 0,
    "designCost" INTEGER NOT NULL DEFAULT 0,
    "conditionTestCost" INTEGER NOT NULL DEFAULT 0,
    "jigReviewCost" INTEGER NOT NULL DEFAULT 0,
    "revisionCost" INTEGER NOT NULL DEFAULT 0,
    "prototypeRiskCost" INTEGER NOT NULL DEFAULT 0,
    "totalCost" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "EstimatePrototype_estimateId_fkey" FOREIGN KEY ("estimateId") REFERENCES "Estimate" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "EstimatePrototype_estimateId_key" ON "EstimatePrototype"("estimateId")`,
  `CREATE TABLE IF NOT EXISTS "EstimateLotRow" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "estimateId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "totalPrice" INTEGER NOT NULL DEFAULT 0,
    "unitPrice" INTEGER NOT NULL DEFAULT 0,
    "cost" INTEGER NOT NULL DEFAULT 0,
    "profit" INTEGER NOT NULL DEFAULT 0,
    "profitRate" REAL NOT NULL DEFAULT 0,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "EstimateLotRow_estimateId_fkey" FOREIGN KEY ("estimateId") REFERENCES "Estimate" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "EstimateActual" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "estimateId" TEXT NOT NULL,
    "actualWorkMinutes" REAL NOT NULL DEFAULT 0,
    "actualMaterialCost" INTEGER NOT NULL DEFAULT 0,
    "memo" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "EstimateActual_estimateId_fkey" FOREIGN KEY ("estimateId") REFERENCES "Estimate" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "EstimateActual_estimateId_key" ON "EstimateActual"("estimateId")`,
  `CREATE TABLE IF NOT EXISTS "Material" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "materialName" TEXT NOT NULL,
    "category" TEXT,
    "thickness" REAL,
    "width" REAL NOT NULL,
    "length" REAL NOT NULL,
    "supplier" TEXT,
    "unitPrice" INTEGER NOT NULL,
    "shippingCost" INTEGER NOT NULL DEFAULT 0,
    "lossRate" REAL NOT NULL DEFAULT 0,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "MachiningCondition" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "material" TEXT NOT NULL,
    "toolDiameter" REAL,
    "toolType" TEXT,
    "rpm" INTEGER,
    "feedRate" REAL,
    "depthPerPass" REAL,
    "stepover" REAL,
    "result" TEXT,
    "memo" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "Setting" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'default',
    "rent" INTEGER NOT NULL DEFAULT 0,
    "electricity" INTEGER NOT NULL DEFAULT 0,
    "communication" INTEGER NOT NULL DEFAULT 0,
    "software" INTEGER NOT NULL DEFAULT 0,
    "vehicle" INTEGER NOT NULL DEFAULT 0,
    "insurance" INTEGER NOT NULL DEFAULT 0,
    "consumables" INTEGER NOT NULL DEFAULT 0,
    "loanRepayment" INTEGER NOT NULL DEFAULT 0,
    "taxReserve" INTEGER NOT NULL DEFAULT 0,
    "livingCost" INTEGER NOT NULL DEFAULT 0,
    "desiredProfit" INTEGER NOT NULL DEFAULT 0,
    "workingDays" INTEGER NOT NULL DEFAULT 20,
    "hoursPerDay" REAL NOT NULL DEFAULT 8,
    "utilizationRate" REAL NOT NULL DEFAULT 0.7,
    "bufferRate" REAL NOT NULL DEFAULT 0.1,
    "baseHourlyRate" INTEGER NOT NULL DEFAULT 0,
    "designRate" INTEGER NOT NULL DEFAULT 0,
    "machineRate" INTEGER NOT NULL DEFAULT 0,
    "setupRate" INTEGER NOT NULL DEFAULT 0,
    "handworkRate" INTEGER NOT NULL DEFAULT 0,
    "finishingRate" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
];

async function main() {
  for (const statement of statements) {
    await prisma.$executeRawUnsafe(statement);
  }
}

main()
  .finally(async () => {
    await prisma.$disconnect();
  });
